version: "3"
services:
  db:
    image:  postgres
    restart: always 
    ports:
      - "5432:5432"
    environment:
       POSTGRES_PASSWORD: asdasdasd111.

      #  run "docker-compose up -d" after lauch docker